### ISSUE TITLE
Rate limit exceeded 

### ISSUE THREAD

**Issue by tejxv** [Sank6/YouTube-Wrapped#1]
how can i fix this
<img width="583" alt="Screenshot 2022-12-03 at 10 15 11 PM" src="https://user-images.githubusercontent.com/54097365/205451886-a63f440d-6e6a-4db5-a628-a19a8d70e050.png">

**Comment by Sank6** [comment]
https://developers.google.com/youtube/v3/docs/errors
https://developers.google.com/youtube/v3/getting-started#quota

I think this means you've exceeded your daily quota. It could be something else though, but its because of the API key.

**Comment by tejxv** [comment]
but i just generated the api key few minutes ago :(

**Comment by Sank6** [comment]
Oh maybe you hadn't linked the YouTube API to the google cloud key?

**Comment by tejxv** [comment]
yeah i figured that out, it's working now thanks :)
