### ISSUE TITLE
Program stuck and won't load after putting API key and watch history file

### ISSUE THREAD

**Issue by HeavenlyDemon100** [Sank6/YouTube-Wrapped#3]
Hey
Does this even work still?
When pasting my API key and uploading the watch history file from google takeout, the program just freezes.
Happens on the standalone version and the online one.

![image](https://user-images.githubusercontent.com/107574383/210421031-4c43c2c0-3bc1-49ab-adca-2e499b2984f9.png)

**Comment by Sank6** [comment]
Was this with the xml or the json version

**Comment by Teerath-Agarwal** [comment]
Same issue, in my case, it was .html file.

**Comment by MNGOwO** [comment]
Same issue with .html, if you force it to output on .JSON it will at least acknowledge the file, but it fails to detect any videos within the provided format.

**Comment by Ventus06** [comment]
Same issue here with HTML , it never loads, waited for around 15minutes but no results

**Comment by tdmiller1** [comment]
@HeavenlyDemon100 Can you try pulling my branch and seeing if that fixes it? I am attempting to update the regex matching for the video Id and the date. It works well locally for me now. Although I am not confident in the data analytics.. Getting ads removed would be very nice.

https://github.com/Sank6/YouTube-Wrapped/pull/5/files

![youtube-wrapped](https://github.com/Sank6/YouTube-Wrapped/assets/28766052/058fd016-d3c3-49d2-9814-3c6bdfef2657)

**Comment by HeavenlyDemon100** [comment]
@tdmiller1 yeah sure I’ll check when I’m home
Also always nice to see another GMM fan :)

**Comment by Sank6** [comment]
Should be fixed
